name: sdp-externals
services:

  # Postgres
  postgres:
    image: postgres:17.6-alpine
#    image: dev0173/sdp-postgres:17.6
    container_name: 'postgres'
    restart: always
    user: ${POSTGRES_ADMIN_USER}
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      SDP_KEYCLOAK_PASSWORD: ${SDP_KEYCLOAK_PASSWORD}                # password for "keycloak" user"
      SDP_DM_USER_PASSWORD: ${SDP_DM_USER_PASSWORD}                  # password for "selfhosted-dm-repo-user" read/write user
      SDP_DM_USER_RO_PASSWORD: ${SDP_DM_USER_RO_PASSWORD}            # password for "selfhosted-dm-repo-user-ro" read-only user
      SDP_DM_DATASOURCE_1_PASSWORD: ${SDP_DM_DATASOURCE_1_PASSWORD}  # password for "datasource-schema-1" user
      SDP_DM_DATASOURCE_2_PASSWORD: ${SDP_DM_DATASOURCE_2_PASSWORD}  # password for "datasource-schema-2" user
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-setup/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  # Postgres Web UI
  adminer:
    image: adminer
    container_name: 'adminer'
    restart: always
    ports:
      - 8090:8080    

  # OpenSearch - Node 1
  opensearch-node1: 
    image: opensearchproject/opensearch:latest 
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch-node1 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-node1,opensearch-node2 # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2 # Nodes eligible to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - plugins.security.ssl.http.enabled=false # Allow HTTP for REST
      - plugins.security.allow_default_init_securityindex=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1 
        hard: -1
      nofile:
        soft: 65536 
        hard: 65536
    healthcheck:
      test: ["CMD", "curl", "-k", "-s", "http://localhost:9200/_plugins/_security/health"]
      interval: 5s
      timeout: 5s
      retries: 60
    volumes:
      - opensearch-data1:/usr/share/opensearch/data 
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network
  
  # OpenSearch - Node 2
  opensearch-node2:
    image: opensearchproject/opensearch:latest 
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
#    depends_on:
#      - opensearch-node1
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net
  
  # Initialise OpenSearch via REST calls to node1 
  opensearch-initialisation:
    image: curlimages/curl:8.9.0
    container_name: opensearch-init
#    depends_on:
#      - opensearch-node1
    environment:
      OPENSEARCH_URL: https://opensearch-node1:9200
      ADMIN_USER: ${OPENSEARCH_ADMIN_USER}
      ADMIN_PASS: ${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      SECURITY_ROLE_NAME: ${OPENSEARCH_SECURITY_ROLE_NAME}
      INTERNAL_USER: ${OPENSEARCH_INTERNAL_USER}
      INTERNAL_USER_PASS: ${OPENSEARCH_INTERNAL_USER_PASS}
    command: ["/bin/sh","/init/initialise.sh"]
    volumes:
      - ./opensearch-setup:/init:ro
      
  # OpenSearch - Dashboards UI
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest 
    container_name: opensearch-dashboards
    depends_on:
      - opensearch-node1
    ports:
      - 5601:5601 
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]' 
    networks:
      - opensearch-net

  # Kafka
  kafka-broker:
    image: apache/kafka:4.1.0
    hostname: kafka-broker
    container_name: kafka-broker
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka-broker:9092,CONTROLLER://kafka-broker:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - kafka-net      

  # A basic UI for Kafka
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker:9092
    depends_on:
      - kafka-broker
    networks:
      - kafka-net      

  # Initialise Kafka
  
  
  
  
  # Mailpit for email testing
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - mailpit-data:/data
    ports:
      - 8025:8025   # Web UI
      - 1025:1025   # SMTP
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1



volumes:
  postgres-data:
  kafka-data:
  opensearch-data1:
  opensearch-data2:
  mailpit-data:

networks:
  opensearch-net:
  kafka-net: